dependencies:
  - name: mongodb
    version: 4.10.1
    repository: https://charts.bitnami.com/bitnami
    alias: mongo-manager
    condition: mongo.install    
  - name: prometheus-operator
    version: 8.7.0
    repository: https://charts.helm.sh/stable
    condition: prometheus.install
    alias: prometheus
  - name: argo
    version: 0.8.5
    repository: https://argoproj.github.io/argo-helm
    condition: argo.install
    alias: argo
  - name: loki-stack
    version: 2.0.2
    repository: https://grafana.github.io/loki/charts
    alias: loki
    condition: loki.install    
  - name: minio
    version: 5.0.32
    repository: https://helm.min.io/
    condition: minio.install
    alias: minio   