{
 "title": "Flink",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "JOB_ID", "label": "Job ID", "query": "flink_jobmanager_job_uptime" }
  ]
 },
 "panels": [
  {
   "title": "Generated and sent transactions per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "generator_generated_per_second",
     "legendFormat": "Created transactions per second"
    },
    { "legendFormat": "Sent transactions per second" }
   ]
  },
  {
   "title": "Records Out per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_id=\"$JOB_ID\"}",
     "legendFormat": "{{operator_name}}"
    },
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_event_time_latency{quantile=\"0.999\"}",
     "legendFormat": "Event time latency"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_event_time_duplicate_latency{quantile=\"0.999\"}",
     "legendFormat": "Event time duplicate latency"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_processing_time_latency{quantile=\"0.999\"}",
     "legendFormat": "Processing time latency"
    }
   ]
  },
  {
   "title": "Records In per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_id=\"$JOB_ID\"}",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "Memory Taskmanager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Committed",
     "legendFormat": "Heap Comitted ({{host}})"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max",
     "legendFormat": "Heap Max ({{host}})"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "Heap Used ({{host}})"
    }
   ]
  },
  {
   "title": "Total checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_totalNumberOfCheckpoints{job_id=\"$JOB_ID\"}"
    },
    {}
   ]
  },
  {
   "title": "Completed checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{job_id=\"$JOB_ID\"}"
    }
   ]
  },
  {
   "title": "Failed checkpoints",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{job_id=\"$JOB_ID\"}"
    }
   ]
  },
  {
   "title": "CPU Load Taskmanager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{job_id=\"$JOB_ID\"}"
    }
   ]
  }
 ]
}