apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: DOCKER_IMAGE_NAME
        imagePullPolicy: Always
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        - containerPort: 9249
          name: metrics
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        - name: HADOOP_CONF_DIR
          value: /opt/flink/etc-hadoop
        volumeMounts:
          - mountPath: '/opt/flink/conf/flink-conf-readonly.yaml'   # path to mount it in container
            name: config-volume                                     # name of the k8s config file
            subPath: 'flink-conf.yaml'
      volumes:
        - configMap:
            name: flink-config
          name: config-volume
