apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongoxp
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: storage-mongo  
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /home/ubuntu/xp/mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: tier
          operator: In
          values:
          - manager
---
# Define Kubernetes PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-manager-mongoxp
  namespace: manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: storage-mongo               