# Just one more PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-pv
  labels:
    name: kafka
    component: kafka
    instance: my-release
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/volume/data/kafka"
