apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: zk
  selector:
    matchLabels:
      component: zookeeper
      instance: zookeeper
      managed-by: Helm
      name: zookeeper
