apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-volume
  labels:
      component: zookeeper
      instance: zookeeper
      managed-by: Helm
      name: zookeeper
spec:
  storageClassName: zk
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/volume/zk"
