apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-submit
spec:
  type: NodePort
  ports:
  - name: rest
    port: 6123
    nodePort: 30123
  selector:
    app: flink
    component: jobmanager
